package com.cts.controller;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import com.cts.dto.NotificationRequestDTO;
import com.cts.dto.NotificationResponseDTO;
import com.cts.service.NotificationService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@RestController
@RequestMapping("/api/v1/notifications")
@AllArgsConstructor
@Tag(name = "Notification Controller", description = "Read in-app notifications generated by booking, payment, and cancellation events")
@Slf4j
public class NotificationController {

    private final NotificationService notificationService;

    @Operation(summary = "Create a notification (internal)")
    @PostMapping
    public ResponseEntity<NotificationResponseDTO> create(@RequestBody NotificationRequestDTO dto) {

        log.info("Creating notification for userId: {} with category: {}", dto.getUserId(), dto.getCategory());

        NotificationResponseDTO response = notificationService.create(dto);

        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    @Operation(summary = "Get the current user's notifications (user id taken from the token)")
    @GetMapping("/me")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<List<NotificationResponseDTO>> getMyNotifications() {

        log.info("Fetching notifications for the current user");

        return new ResponseEntity<>(notificationService.getMyNotifications(), HttpStatus.OK);
    }

    @Operation(summary = "Get all notifications for a user (staff lookup)")
    @GetMapping("/{userId}")
    @PreAuthorize("hasAnyRole('TRAVEL_AGENT','ADMIN')")
    public ResponseEntity<?> getUserNotifications(@PathVariable Long userId) {

        log.info("Fetching notifications for userId: {}", userId);

        List<NotificationResponseDTO> list1 =
                notificationService.getUserNotifications(userId);

        log.info("Fetched {} notifications for userId: {}", list1.size(), userId);

        return new ResponseEntity<>(list1, HttpStatus.OK);
    }

    @Operation(summary = "Mark one of the current user's notifications as read")
    @PatchMapping("/{id}/read")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<NotificationResponseDTO> markAsRead(@PathVariable Long id) {

        log.info("Marking notification {} as read", id);

        return new ResponseEntity<>(notificationService.markAsRead(id), HttpStatus.OK);
    }

    @Operation(summary = "Mark all of the current user's notifications as read; returns the number updated")
    @PatchMapping("/read-all")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<Integer> markAllAsRead() {

        log.info("Marking all notifications as read for the current user");

        return new ResponseEntity<>(notificationService.markAllAsRead(), HttpStatus.OK);
    }
}
