server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel360_booking_db?createDatabaseIfNotExist=true

resilience4j:
  circuitbreaker:
    instances:
      NOTIFICATION-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
      USER-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
      CATALOG-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
